### ISSUE TITLE
Should we consider the swish activation function?

### ISSUE THREAD

**Issue by asdf2014** [hankcs/ID-CNN-CWS#1]
We could improve the `apply_nonlinearity` function by adding swish activation function. I notice the tensorflow already implement the swish in [ops/nn_impl.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/nn_impl.py#L295).

**Comment by hankcs** [comment]
Sure, you are alway encouraged to try different modifications. You can add this new feature into the  [command line interface](https://github.com/hankcs/ID-CNN-CWS/blob/master/train.py#L593).

Thanks.

**Comment by asdf2014** [comment]
Okay, i will create that PR later. Thanks for your comment.

**Comment by asdf2014** [comment]
Added [PR#2](https://github.com/hankcs/ID-CNN-CWS/pull/2).
