### ISSUE TITLE
参数详解

### ISSUE THREAD

**Issue by pz973494545** [hankcs/ID-CNN-CWS#4]
非常感谢分享！对有些参数不是很明白，希望有一份参数详解，比如参数的意义，用处，默认值，如何设置等。初学者，见谅
batch_size : 128
beta1 : 0.9
beta2 : 0.9
block_repeats : 1
char_dim : 0
char_input_dropout : 1.0
char_model : lstm
char_tok_dim : 0
clip_norm : 5.0    #例如这个参数
dev_dir : dataset/pku/dev
documents : False
embed_dim : 100
embeddings : data/embeddings/character.vec
epsilon : 1e-06
evaluate_only : False
filter_size : 3
hidden_dropout : 0.55
input_dropout : 0.85
l2 : 1e-05
layers : {'conv1': {'dilation': 1, 'width': 3, 'filters': 400, 'initialization': 'identity', 'take': false}, 'conv2': {'dilation': 2, 'width': 3, 'filters': 400, 'initialization': 'identity', 'take': false}, 'conv3': {'dilation': 1, 'width': 3, 'filters': 400, 'initialization': 'identity', 'take': true}}
load_dir :
log_every : 2
loss : mean
lr : 0.001
lr_decay : 1.0
lstm_dim : 400
maps_dir : dataset/pku/train
margin : 0.0
master :
max_context_epochs : 100
max_epochs : 100
max_finetune_epochs : 100
memmap_train : True
middle_dropout : 0.85
model : cnn
model_dir : result/pku/cnn/2017-11-22_10-54-48
nonlinearity : relu
ontonotes : False
optimizer : adam
print_preds : False
projection : False
regularize_drop_penalty : 1e-05
save_min : 0.0
shape_dim : 50
share_repeats : True
start_end : False
train_dir : dataset/pku/train
train_eval : False
until_convergence : False
viterbi : False
word_dropout : 0.85
num classes: 4
dataset/pku/train/sizes.txt
num train examples: 129916
num train tokens: 1609674
dataset/pku/dev
dataset/pku/dev/sizes.txt
num dev examples: 14436
num dev tokens: 178741
{'': 0}
Loaded 4654/4679 embeddings (99.47% coverage)

**Comment by hankcs** [comment]
http://www.hankcs.com/nlp/cs224n-rnn-and-language-models.html#h3-6

I'll close this issue, as this repo only serves for CWS research. For beginners, you can self-study more basic theories in graduate courses like cs224n.
